spring:
  application:
    name: spring-todo
  datasource:
    url: jdbc:mysql://localhost:3306/todo?createDatabaseIfNotExist=true
    username: root
    password: sqlAdmin1!
  jpa:
    show-sql: true
